CustomCommand: "/ban {player} Using blocked commands"

Commands:
  - "//sphere"
  - "//br"
  - "//brush"
  - "//cyl"
  - "//set"
  - "/ept"
  - "/pt"
  - "//replace"
  - "//hsphere"
  - "//fill"
  - "//fillr"
  - "/setblock"
  - "/execute"
  - "//generate"
  - "//spike"
  - "//rock"
  - "//calculate"
  - "//loft"
  - "//expand"
  - "//road"
  - "//deform"
  - "//air"
  - "//stack"

Whitelist:
   - "AdminPlayer"